/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generation mode. 'section' generates editor-selected sections via generate_section. 'page' uses plan_page → generate_section for AI-planned full-page generation.
 */
export type Mode = "section" | "page";
/**
 * Ordered list of component types to generate (section mode only). E.g. ['faq'] for a single section, or ['features', 'testimonials', 'cta'] for multiple. Ignored in page mode.
 */
export type ComponentTypes = string[];
/**
 * Deprecated — in page mode, section count is determined by plan_page. In section mode, determined by componentTypes array length. Kept for backward compat.
 */
export type SectionCountDeprecated = number;
/**
 * Whether to include the current story as main context
 */
export type IncludeStory = boolean;
/**
 * Whether to use an idea as part of the context
 */
export type UseIdea = boolean;
/**
 * Additional related stories to include as context
 */
export type RelatedStories = string[];
/**
 * In section mode: prompt describing the section(s) content. In page mode: intent for page planning.
 */
export type UserPrompt = string;
/**
 * Optional system prompt override (default: auto-generated with site context)
 */
export type SystemPrompt = string;
/**
 * Content type for generation. Auto-detected from story if not set.
 */
export type ContentType = "page" | "blog-post" | "blog-overview";
/**
 * Optional slug prefix filter for pattern analysis (e.g. 'case-studies/' to match style of that section)
 */
export type PatternSlugPrefix = string;
/**
 * Upload generated image URLs to Storyblok CDN on save
 */
export type UploadAssets = boolean;

/**
 * Component used to create new website content using AI prompts
 */
export interface PrompterProps {
  mode?: Mode;
  componentTypes?: ComponentTypes;
  sections?: SectionCountDeprecated;
  includeStory?: IncludeStory;
  useIdea?: UseIdea;
  relatedStories?: RelatedStories;
  userPrompt?: UserPrompt;
  systemPrompt?: SystemPrompt;
  contentType?: ContentType;
  startsWith?: PatternSlugPrefix;
  uploadAssets?: UploadAssets;
}
