/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generation mode. 'section' generates editor-selected sections.
 * 'page' uses plan_page for AI-planned full-page generation.
 */
export type PrompterMode = "section" | "page";
/**
 * @deprecated Determined by componentTypes length or plan_page. Kept for backward compat.
 */
export type SectionCount = number;
/**
 * Whether to include the current story as main context
 */
export type IncludeStory = boolean;
/**
 * Whether to use an idea as part of the context
 */
export type UseIdea = boolean;
/**
 * Additional related stories to include as context
 */
export type RelatedStories = string[];
/**
 * Prompt describing the content or page intent
 */
export type UserPrompt = string;
/**
 * Optional system prompt override
 */
export type SystemPrompt = string;
/**
 * Ordered list of component types to generate (section mode only)
 */
export type ComponentTypes = string[];
/**
 * Content type for generation. Auto-detected from story if not set.
 */
export type ContentType = "page" | "blog-post" | "blog-overview";
/**
 * Optional slug prefix filter for pattern analysis
 */
export type StartsWith = string;
/**
 * Upload generated image URLs to Storyblok CDN on save
 */
export type UploadAssets = boolean;

/**
 * Component used to create new website content using AI prompts
 */
export interface PrompterProps {
  mode?: PrompterMode;
  componentTypes?: ComponentTypes;
  /** @deprecated */
  sections?: SectionCount;
  includeStory?: IncludeStory;
  useIdea?: UseIdea;
  relatedStories?: RelatedStories;
  userPrompt?: UserPrompt;
  systemPrompt?: SystemPrompt;
  contentType?: ContentType;
  startsWith?: StartsWith;
  uploadAssets?: UploadAssets;
}
