/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventAppointmentProps} from "../event-appointment/EventAppointmentProps";

/**
 * List of dates of the event
 */
export type Dates = EventAppointmentProps[];
/**
 * Name of the event location
 */
export type LocationName = string;
/**
 * Spacious is recommended for 1-2 appointments, Compact for more than 2.
 */
export type DisplayMode = "spacious" | "compact";
/**
 * Address of the appointment
 */
export type Address = string;
/**
 * Links related to the event location
 */
export type Links = {
  url: string;
  label: string;
  /**
   * Open link in a new tab
   */
  newTab?: boolean;
}[];

/**
 * Event location component for displaying event dates, location details, and related links.
 */
export interface EventLocationProps {
  dates?: Dates;
  locationName?: LocationName;
  displayMode?: DisplayMode;
  address?: Address;
  links?: Links;
}
