/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human-readable name shown in the theme picker (e.g. 'Dark Mode', 'Brand Neon')
 */
export type ThemeName = string;
/**
 * Structured branding token JSON — managed by the Design Tokens Editor, do not edit manually
 */
export type TokenConfigurationJSON = string;
/**
 * Auto-generated CSS custom properties — computed from tokens JSON on save, revalidated on deploy
 */
export type GeneratedCSS = string;
/**
 * Marks this theme as system-managed. System themes are synced from the Design System and cannot be modified or deleted by users.
 */
export type SystemTheme = boolean;

/**
 * A named branding token theme that can be selected on pages and global settings
 */
export interface TokenThemeProps {
  name: ThemeName;
  tokens?: TokenConfigurationJSON;
  css?: GeneratedCSS;
  system?: SystemTheme;
}
