/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { LogoProps } from "../logo/LogoProps";

/**
 * Toggle the inversion of the flyout navigation
 */
export type FlyoutInverted = boolean;
/**
 * Toggle the CTA
 */
export type ToggleCTA = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Target that should be linked, makes the button behave like a link semantically
 */
export type Target = string;

export interface NavMainProps {
  /**
   * Referenced component LogoProps
   */
  logo: LogoProps;
  flyoutInverted?: FlyoutInverted;
  navItems?: {
    href: string;
    label: string;
    active?: boolean;
    navItems?: {
      href?: string;
      label?: string;
      active?: boolean;
    }[];
  }[];
  cta?: CTA;
}
/**
 * Add a CTA to the Navigation
 */
export interface CTA {
  toggle?: ToggleCTA;
  label?: Label;
  target?: Target;
}
