/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date of the event
 */
export type Date = string;
/**
 * The month of the event
 */
export type Month = string;
/**
 * The day of the event
 */
export type Day = string;
/**
 * Title of the event
 */
export type Headline = string;
/**
 * Location of the event
 */
export type Location = string;
/**
 * The event entry URL to link
 */
export type URL = string;
/**
 * Text for the call to action
 */
export type CallToAction = string;
/**
 * ARIA label for accessibility
 */
export type ARIALabel = string;

/**
 * Display an event teaser with date, title and location
 */
export interface EventLatestTeaserProps {
  date: Date;
  calendar?: Calendar;
  title: Headline;
  location: Location;
  url?: URL;
  cta?: CallToAction;
  ariaLabel?: ARIALabel;
  className?: string;
}
/**
 * Calendar icon to display the date
 */
export interface Calendar {
  month?: Month;
  day?: Day;
}
