/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of categories to filter appointments
 */
export type Label = string[];

/**
 * Event filter component for filtering events based on date and categories.
 */
export interface EventFilterProps {
  datePicker?: {
    /**
     * Title for the date picker
     */
    title?: string;
    dateFromInput?: {
      /**
       * Label for the date-from input
       */
      label?: string;
      /**
       * Placeholder text for the date-from input
       */
      placeholder?: string;
    };
    dateToInput?: {
      /**
       * Label for the date-to input
       */
      label?: string;
      /**
       * Placeholder text for the date-to input
       */
      placeholder?: string;
    };
    /**
     * Toggle to enable or disable the date picker
     */
    toggle?: boolean;
  };
  categories?: {
    /**
     * Title for the categories filter
     */
    title?: string;
    categoryCheckboxes?: Label;
    /**
     * Toggle to enable or disable the category filter
     */
    toggle?: boolean;
  };
  applyButton?: {
    /**
     * Label for the button
     */
    label?: string;
    /**
     * Function to call on button click
     */
    onClick?: string;
  };
  resetButton?: {
    /**
     * Label for the button
     */
    label?: string;
    /**
     * Function to call on button click
     */
    onClick?: string;
  };
}
