/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Placeholder text for the search input field.
 */
export type Placeholder = string;

/**
 * Search bar component for user input and search functionality.
 */
export interface SearchBarProps {
  placeholder?: Placeholder;
  /**
   * Text displayed on the search button.
   */
  buttonText?: string;
  /**
   * Additional information or instructions related to the search functionality.
   */
  hint?: string;
  /**
   * Text to display when offering alternative results.
   */
  alternativeText?: string;
  /**
   * The alternative result to display when offering suggestions.
   */
  alternativeResult?: string;
}
