/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Label of the event registration
 */
export type Label = string;
/**
 * Title of the event
 */
export type Title = string;
/**
 * URL to the event details
 */
export type URL = string;
/**
 * Text for the link to the event details
 */
export type LinkText = string;
/**
 * Date of the registration
 */
export type Date = string;
/**
 * Time of the registration
 */
export type Time = string;
/**
 * Label for the email input
 */
export type Label1 = string;
/**
 * Placeholder text for the email input
 */
export type Placeholder = string;
/**
 * Label for the confirmation checkbox
 */
export type Label2 = string;
/**
 * Text indicating that the checkbox is mandatory
 */
export type MandatoryText = string;
/**
 * Label for the call to action button
 */
export type ButtonLabel = string;
/**
 * Aria label for the cta button
 */
export type AriaLabel = string;

/**
 * Event registration component for users to register for events.
 */
export interface EventRegistrationProps {
  label?: Label;
  title?: Title;
  link?: Link;
  date?: Date;
  time?: Time;
  location?: Location;
  nameInput?: NameInput;
  emailInput?: EmailInput;
  confirmationCheckboxLabel?: Label2;
  mandatoryText?: MandatoryText;
  cta?: CallToAction;
}
/**
 * Link to the event details
 */
export interface Link {
  url?: URL;
  text?: LinkText;
}
/**
 * Location of the event
 */
export interface Location {
  name?: string;
  address?: string;
}
/**
 * Input field for the name
 */
export interface NameInput {
  label?: string;
  placeholder?: string;
}
/**
 * Input field for the email
 */
export interface EmailInput {
  label?: Label1;
  placeholder?: Placeholder;
}
export interface CallToAction {
  label?: ButtonLabel;
  url?: string;
  ariaLabel?: AriaLabel;
}
