/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Search filter component for filtering search results by categories.
 */
export interface SearchFilterProps {
  /**
   * The title of the search filter.
   */
  title?: string;
  /**
   * The categories to filter by.
   */
  categories?: {
    /**
     * The name of the category.
     */
    title?: string;
    /**
     * The number of items in the category.
     */
    amount?: string;
    /**
     * The URL to filter by this category.
     */
    url?: string;
  }[];
}
