#!/usr/bin/env node
/**
 * Build-time CSS extraction for ext-apps preview templates.
 *
 * Reads `@kickstartds/design-system/global.css` from node_modules
 * and writes it as a TypeScript string constant to
 * `src/ui/tokens.generated.ts`.
 *
 * This CSS is inlined into the HTML preview templates so that
 * `renderToStaticMarkup` output is properly styled in the ext-apps
 * sandboxed iframe — same class names, same visual result.
 *
 * Run via: `node scripts/extract-tokens.js`
 * Or:      `pnpm run build:tokens`
 *
 * @see PRD Section 6.4 — Design Token Integration
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Resolve the global.css path from the installed package
let globalCssPath;
try {
  // Resolve the package.json first, then construct the CSS path
  const pkgPath = require.resolve(
    "@kickstartds/design-system/package.json"
  );
  globalCssPath = resolve(dirname(pkgPath), "dist", "global.css");
} catch {
  console.error(
    "Error: @kickstartds/design-system not found in node_modules."
  );
  console.error("Run `pnpm install` first.");
  process.exit(1);
}

if (!existsSync(globalCssPath)) {
  console.error(`Error: global.css not found at ${globalCssPath}`);
  process.exit(1);
}

const css = readFileSync(globalCssPath, "utf-8");
const outputPath = resolve(__dirname, "..", "src", "ui", "tokens.generated.ts");

// Escape backticks and ${} template literals in the CSS content
const escapedCss = css
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const output = `/**
 * AUTO-GENERATED — Do not edit manually.
 *
 * kickstartDS Design System CSS extracted from
 * @kickstartds/design-system/global.css at build time.
 *
 * Generated by: scripts/extract-tokens.js
 * Source: ${globalCssPath.split("node_modules/").pop()}
 * Size: ${(css.length / 1024).toFixed(1)} KB
 *
 * This CSS is inlined into ext-apps preview HTML templates so that
 * renderToStaticMarkup output renders with correct styles.
 */

/** Full kickstartDS Design System CSS (normalize + tokens + components) */
export const KDS_GLOBAL_CSS = \`${escapedCss}\`;
`;

writeFileSync(outputPath, output, "utf-8");
console.log(
  `✅ Extracted ${(css.length / 1024).toFixed(1)} KB of CSS → ${outputPath
    .split("packages/")
    .pop()}`
);
