/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The questions and answers in the Faq section
 *
 * @minItems 1
 */
export type Questions = [Question, ...Question[]];
/**
 * The question
 */
export type Question1 = string;
/**
 * The answer to the question
 */
export type Answer = string;

/**
 * Component used to display a Faq section
 */
export interface FaqProps {
  questions: Questions;
}
export interface Question {
  question: Question1;
  answer?: Answer;
}
