/**
 * Schema preparation for OpenAI structured output.
 *
 * Transforms kickstartDS Design System JSON Schemas into a format compatible
 * with OpenAI's structured output (`response_format: json_schema`).
 *
 * The OpenAI API has constraints that vanilla JSON Schemas don't:
 * - No `const` keyword → replaced with `type__<value>` string discriminators
 * - No unsupported keywords (`format`, `$id`, `$schema`, `minItems`, etc.)
 * - `additionalProperties: false` required on every object
 * - All properties must be listed in `required`
 * - Limits on total property count (< 5000) and enum values (< 1000)
 *
 * Pure functions — no framework dependencies. Usable from API routes,
 * MCP servers, n8n nodes, or browser-side React components.
 */

// json-schema-traverse ships a CJS default export.
// In ESM we may receive `{ default: fn }` or `fn` directly depending on the
// bundler / runtime, so we normalise here.
import _schemaTraverse from "json-schema-traverse";
const schemaTraverse: typeof _schemaTraverse =
  typeof (_schemaTraverse as any).default === "function"
    ? (_schemaTraverse as any).default
    : _schemaTraverse;

type TraverseCallback = _schemaTraverse.Callback;

// ─── Static data ──────────────────────────────────────────────────────

/**
 * Keywords that OpenAI's structured output does not support and must be
 * stripped before sending the schema.
 */
export const UNSUPPORTED_KEYWORDS = [
  "format",
  "minItems",
  "maxItems",
  "minimum",
  "maximum",
  "examples",
  "default",
  "$id",
  "$schema",
] as const;

/**
 * Properties that are layout / styling concerns and should generally not
 * be generated by AI (they are set at the CMS level instead).
 *
 * Note: `spaceBefore`, `spaceAfter`, and `variant` were removed from this
 * list — they are now annotated with contextual descriptions instead of
 * being dropped. See `PROPERTIES_TO_ANNOTATE`.
 */
export const DEFAULT_PROPERTIES_TO_DROP = [
  "backgroundColor",
  "backgroundImage",
  "spotlight",
  "textColor",
] as const;

/**
 * Properties that stay in the schema but get enriched descriptions.
 * These are fields where the LLM can make informed choices with guidance.
 */
export const PROPERTIES_TO_ANNOTATE = [
  "spaceBefore",
  "spaceAfter",
  "variant",
] as const;

/**
 * Contextual descriptions for fields that benefit from guidance.
 * Injected into the `description` property during schema preparation.
 */
export const FIELD_ANNOTATIONS: Record<string, string> = {
  spaceBefore:
    "Spacing before this section. Use 'none' for the first section on a page, 'default' for most sections, 'small' when tightly coupled with the previous section.",
  spaceAfter:
    "Spacing after this section. Use 'default' for most sections, 'small' when the next section is visually related, 'none' rarely.",
  headerSpacing:
    "Extra top spacing for a floating/transparent header. Only true on the first section of a page, and only when the header overlays content.",
  width:
    "Section width. 'default' for most content. 'full' for full-bleed heroes or visual sections. 'narrow' for focused text content.",
  content_mode:
    "Content layout mode. 'default' for single-component or standard layout. 'tile' for multi-item grids (features, cards). 'list' for vertically stacked diverse items. 'slider' only with 3+ items.",
  content_tileWidth:
    "Min-width for grid tiles. Only meaningful when content_mode is 'tile'. 'default' for most grids.",
};

/**
 * Component names that are available for AI content generation.
 *
 * @deprecated Use `buildValidationRules(schema).allKnownComponents` from
 *   `./validate.js` instead. This hardcoded list will be removed in a future
 *   major version.
 */
export const SUPPORTED_COMPONENTS = [
  "blog-teaser",
  "business-card",
  "contact",
  "content-nav",
  "cta",
  "divider",
  "downloads",
  "faq",
  "features",
  "gallery",
  "headline",
  "hero",
  "image-story",
  "image-text",
  "info-table",
  "logos",
  // "mosaic",
  "page",
  "section",
  // "split-even",
  // "split-weighted",
  "stats",
  "teaser-card",
  "testimonials",
  "text",
  "video-curtain",
] as const;

/**
 * Maps parent component names to the property key that holds their
 * sub-component arrays (e.g. `downloads` → `download`).
 *
 * @deprecated Use `buildValidationRules(schema).subComponentMap` from
 *   `./validate.js` instead. This hardcoded map will be removed in a future
 *   major version.
 */
export const SUB_COMPONENT_MAP: Record<string, string> = {
  downloads: "download",
  faq: "questions",
  features: "feature",
  gallery: "images",
  logos: "logo",
  mosaic: "tile",
  stats: "stat",
  testimonials: "testimonial",
} as const;

// ─── Helpers ──────────────────────────────────────────────────────────

/**
 * Extract the component name from a JSON Schema `$id` URI.
 * E.g. `"http://…/hero.schema.json"` → `"hero"`.
 */
export function getSchemaName(schemaId: string): string {
  return (schemaId && schemaId.split("/").pop()?.split(".").shift()) || "";
}

// ─── Types ────────────────────────────────────────────────────────────

/** Options for `prepareSchemaForOpenAi`. */
export interface PrepareSchemaOptions {
  /**
   * Number of items to generate in the primary root array.
   * Sets both `minItems` and `maxItems` on that array.
   * (For page-like schemas this controls the section count.)
   */
  sections?: number;
  /**
   * Whitelist of component names to include.
   * Defaults to `SUPPORTED_COMPONENTS` (or `validationRules.allKnownComponents`
   * when validation rules are provided).
   */
  allowedComponents?: string[];
  /**
   * Property names to strip from every component schema.
   * Defaults to `DEFAULT_PROPERTIES_TO_DROP`.
   */
  propertiesToDrop?: string[];
  /**
   * Schema-derived validation rules from `buildValidationRules()`.
   * When provided, `allKnownComponents` is used as the default component
   * list and `subComponentMap` is used instead of the hardcoded
   * `SUB_COMPONENT_MAP`.
   */
  validationRules?: {
    allKnownComponents: Set<string>;
    subComponentMap: Record<string, string>;
    rootArrayFields?: string[];
    containerSlots?: Map<string, Set<string>>;
  };
  /**
   * Name of the primary root array field to apply `sections` (min/maxItems)
   * constraints to. When omitted, auto-detected from the schema's first
   * root-level array property or from `validationRules.rootArrayFields[0]`.
   */
  rootArrayField?: string;
  /**
   * Root-level property names to exclude from the prepared schema
   * (e.g. `["header", "footer", "seo"]`). These properties are deleted
   * from the cloned schema before OpenAI transformation.
   *
   * When omitted, auto-detected via `detectDefaultExcludes()`:
   * properties named `header`, `footer`, `token`, `seo` are excluded
   * by default.
   */
  rootPropertiesToExclude?: string[];
  /**
   * Content type name, used to set the envelope name
   * (e.g. `"blog-post"` → `"blog_post_response"`).
   * Defaults to `"page"`.
   */
  contentType?: string;
}

/** The OpenAI-compatible schema envelope. */
export interface OpenAiSchemaEnvelope {
  name: string;
  strict: boolean;
  schema: Record<string, any>;
}

/** Validation diagnostics returned alongside the prepared schema. */
export interface SchemaValidation {
  totalProperties: number;
  maxDepth: number;
  enumValueCount: number;
  warnings: string[];
}

/** Full result of `prepareSchemaForOpenAi`. */
export interface PreparedSchema {
  /** Schema envelope ready to pass to OpenAI `response_format.json_schema`. */
  envelope: OpenAiSchemaEnvelope;
  /**
   * Map of component type name → its original (pre-transformation) schema.
   * Used later by `processOpenAiResponse` to merge defaults.
   */
  schemaMap: Record<string, Record<string, any>>;
  /** Validation diagnostics. */
  validation: SchemaValidation;
}

// ─── Core API ─────────────────────────────────────────────────────────

/**
 * Transform a dereffed page schema into an OpenAI-compatible structured
 * output schema.
 *
 * This is the main entry point — it runs all 15 transformation passes
 * that were previously embedded in the PrompterComponent.
 *
 * @param pageSchema - The fully dereferenced page JSON Schema from
 *   `@kickstartds/design-system/page/page.schema.dereffed.json`.
 * @param options - Optional configuration.
 * @returns The prepared schema envelope + component schema map.
 */
export function prepareSchemaForOpenAi(
  pageSchema: Record<string, any>,
  options: PrepareSchemaOptions = {}
): PreparedSchema {
  const {
    sections,
    propertiesToDrop = DEFAULT_PROPERTIES_TO_DROP as unknown as string[],
    validationRules,
  } = options;

  // Use schema-derived component list when available, fall back to hardcoded
  const defaultComponents: string[] = validationRules
    ? [...validationRules.allKnownComponents]
    : (SUPPORTED_COMPONENTS as unknown as string[]);
  const allowedComponents = options.allowedComponents || defaultComponents;

  // ── Resolve nested container slot types ─────────────────────────
  // When a specific componentType is requested (e.g. "split-even"), the
  // allowedComponents list only contains that type + "section". But
  // container components like split-even and split-weighted have nested
  // polymorphic slots (firstComponents, mainComponents, etc.) whose
  // child components also need type const injection. Without this,
  // child components get no `type` discriminator and end up missing
  // their `component` identifier in Storyblok.
  //
  // We build a separate expanded set for type const injection while
  // keeping the original allowedComponents for section-level filtering,
  // so that only the requested component appears at the top level.
  let nestedSlotTypes: Set<string> | null = null;
  if (options.allowedComponents && validationRules?.containerSlots) {
    nestedSlotTypes = new Set<string>();
    for (const componentName of allowedComponents) {
      for (const [slotPath, slotTypes] of validationRules.containerSlots) {
        // Match slots owned by this component (e.g. "split-even.firstComponents")
        if (slotPath.startsWith(`${componentName}.`)) {
          for (const childType of slotTypes) {
            if (!allowedComponents.includes(childType)) {
              nestedSlotTypes.add(childType);
            }
          }
        }
      }
    }
    if (nestedSlotTypes.size === 0) nestedSlotTypes = null;
  }

  // Use schema-derived sub-component map when available
  const subComponentMap: Record<string, string> = validationRules
    ? validationRules.subComponentMap
    : SUB_COMPONENT_MAP;

  // Mutable map that gets populated during traversal
  const schemaMap: Record<string, Record<string, any>> = {};

  // Validation accumulators
  const allProperties = new Set<string>();
  let maxDepth = 0;
  let enumValueCount = 0;
  const warnings: string[] = [];

  // ── Pass 0: Collect component schemas by type const ─────────────
  const collectSchemas: TraverseCallback = (schema) => {
    if (
      schema.properties &&
      schema.properties.type &&
      schema.properties.type.const
    ) {
      schemaMap[schema.properties.type.const] = structuredClone(schema);
    }
  };

  // Run on the *original* schema before cloning
  schemaTraverse(pageSchema, collectSchemas);

  // Clone so we don't mutate the caller's object
  const clonedSchema = structuredClone(pageSchema);

  // ── Structural pruning ──────────────────────────────────────────
  // Remove root-level properties that shouldn't be generated by AI
  const excludeProps =
    options.rootPropertiesToExclude || detectDefaultExcludes(clonedSchema);
  for (const prop of excludeProps) {
    if (clonedSchema.properties[prop]) {
      delete clonedSchema.properties[prop];
    }
  }

  // Determine the primary root array field for minItems/maxItems constraints
  const primaryArrayField =
    options.rootArrayField ||
    options.validationRules?.rootArrayFields?.[0] ||
    detectPrimaryRootArray(clonedSchema);

  if (
    sections !== undefined &&
    primaryArrayField &&
    clonedSchema.properties[primaryArrayField]
  ) {
    clonedSchema.properties[primaryArrayField].minItems = sections;
    clonedSchema.properties[primaryArrayField].maxItems = sections;
  }

  // Add type consts to sub-component arrays inside ALL root-level
  // polymorphic container slots (not just "section")
  const rootArrayFields =
    options.validationRules?.rootArrayFields ||
    detectRootArrayFields(clonedSchema);
  for (const arrayField of rootArrayFields) {
    const rootArray = clonedSchema.properties[arrayField];
    if (!rootArray?.items) continue;
    // Walk into the items to find polymorphic anyOf slots
    addSubComponentTypeConsts(rootArray.items, subComponentMap);
  }

  // ── Traverse-based transformation passes ────────────────────────

  const addTypeConsts: TraverseCallback = (schema) => {
    if (schema && schema.anyOf) {
      schema.anyOf.forEach((component: any) => {
        if (component.$id) {
          const componentName = getSchemaName(component.$id);
          if (
            (allowedComponents.includes(componentName) ||
              nestedSlotTypes?.has(componentName)) &&
            !component.properties?.type
          ) {
            component.properties.type = { const: componentName };
          }
        }
      });
    }
  };

  const filterComponents: TraverseCallback = (schema) => {
    if (schema && schema.anyOf) {
      // Only filter anyOf arrays that contain items claimed by
      // allowedComponents. Nested container slots (e.g. inside
      // split-even.firstComponents) have type consts from nestedSlotTypes
      // but those don't match allowedComponents, so hasClaimedItems
      // returns false and the nested anyOf is left untouched — all child
      // components remain available for generation.
      const hasClaimedItems = schema.anyOf.some(
        (component: any) =>
          component.properties?.type?.const &&
          allowedComponents.includes(component.properties.type.const)
      );
      if (hasClaimedItems) {
        schema.anyOf = schema.anyOf.filter((component: any) => {
          return (
            component.properties?.type &&
            component.properties.type.const &&
            allowedComponents.includes(component.properties.type.const)
          );
        });
      }
    }
  };

  // Safety net: remove any array properties whose items.anyOf became
  // empty after filtering (should not happen with the guard above, but
  // kept as a defensive measure). OpenAI rejects empty anyOf arrays.
  const removeEmptyAnyOf: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (
      schema &&
      schema.type === "array" &&
      schema.items?.anyOf &&
      Array.isArray(schema.items.anyOf) &&
      schema.items.anyOf.length === 0 &&
      keyIndex &&
      parentSchema?.properties?.[keyIndex]
    ) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const deleteConsts: TraverseCallback = (
    schema,
    jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    parentKeyword,
    parentSchema
  ) => {
    if (schema.const && parentKeyword === "properties" && parentSchema) {
      const propName = jsonPtr.split("/").pop();
      if (propName === "type") {
        const type: Record<string, any> = { properties: {} };
        type.properties[`type__${schema.const}`] = {
          type: "string",
          title: "Type of component",
          description: `A field always being set to the value '${schema.const}'`,
        };
        parentSchema.properties = {
          ...type.properties,
          ...parentSchema.properties,
        };
      }
      if (propName) {
        delete parentSchema.properties[propName];
      }
    }
  };

  const removeImageFormatProperties: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    _parentSchema,
    _keyIndex
  ) => {
    if (schema.format === "image" || schema.format === "video") {
      delete schema.format;
    }
  };

  const removeIconProperties: TraverseCallback = (
    _schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (keyIndex === "icon" && parentSchema?.properties?.[keyIndex]) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const removeUnsupportedProperties: TraverseCallback = (
    _schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (
      keyIndex &&
      typeof keyIndex === "string" &&
      propertiesToDrop.includes(keyIndex) &&
      parentSchema?.properties?.[keyIndex]
    ) {
      delete parentSchema.properties[keyIndex];
    }
  };

  // Enrich field descriptions with contextual guidance
  const annotateFieldDescriptions: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    _parentSchema,
    keyIndex
  ) => {
    if (
      keyIndex &&
      typeof keyIndex === "string" &&
      FIELD_ANNOTATIONS[keyIndex] &&
      schema &&
      typeof schema === "object"
    ) {
      schema.description = FIELD_ANNOTATIONS[keyIndex];
    }
  };

  const removeUnsupportedKeywords: TraverseCallback = (schema) => {
    for (const key of UNSUPPORTED_KEYWORDS) {
      if (Object.prototype.hasOwnProperty.call(schema, key)) {
        delete schema[key];
      }
    }
  };

  const removeEmptyObjects: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (
      schema.type === "object" &&
      schema.properties &&
      !Object.keys(schema.properties).length &&
      keyIndex &&
      parentSchema?.properties?.[keyIndex]
    ) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const denyAdditionalProperties: TraverseCallback = (schema) => {
    if (schema.type === "object") {
      schema.additionalProperties = false;
    }
  };

  const makeRequired: TraverseCallback = (schema) => {
    if (schema.type === "object" && schema.properties) {
      schema.required = Object.keys(schema.properties);
    }
  };

  // ── Validation passes ───────────────────────────────────────────

  const collectProperties: TraverseCallback = (
    _schema,
    jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    parentKeyword
  ) => {
    if (
      jsonPtr &&
      parentKeyword === "properties" &&
      !allProperties.has(jsonPtr)
    ) {
      allProperties.add(jsonPtr);
    }
  };

  const countDepth: TraverseCallback = (_schema, jsonPtr) => {
    const depth = jsonPtr.split("/properties/").length;
    maxDepth = Math.max(depth, maxDepth);
  };

  const countEnums: TraverseCallback = (schema) => {
    if (schema.enum) {
      enumValueCount += schema.enum.length;
    }
  };

  // ── Execute all passes ──────────────────────────────────────────
  [
    addTypeConsts,
    filterComponents,
    removeEmptyAnyOf,
    deleteConsts,
    removeImageFormatProperties,
    removeIconProperties,
    removeUnsupportedProperties,
    annotateFieldDescriptions,
    removeUnsupportedKeywords,
    removeEmptyObjects,
    denyAdditionalProperties,
    makeRequired,
    collectProperties,
    countDepth,
    countEnums,
  ].forEach((fn) => {
    schemaTraverse(clonedSchema, fn);
  });

  // ── Collect warnings ────────────────────────────────────────────
  if (allProperties.size > 5000) {
    warnings.push(
      `Property count (${allProperties.size}) exceeds OpenAI limit of 5000.`
    );
  }
  if (enumValueCount > 1000) {
    warnings.push(
      `Enum value count (${enumValueCount}) exceeds OpenAI limit of 1000.`
    );
    console.error(JSON.stringify(clonedSchema, null, 2));
  }

  const contentType = options.contentType || "page";
  const envelopeName = `${contentType.replace(/-/g, "_")}_response`;

  return {
    envelope: {
      name: envelopeName,
      strict: true,
      schema: clonedSchema,
    },
    schemaMap,
    validation: {
      totalProperties: allProperties.size,
      maxDepth,
      enumValueCount,
      warnings,
    },
  };
}

/**
 * Derive a single-component OpenAI-ready schema from the full page schema.
 *
 * This is useful for generating content for one specific component type
 * (e.g. "hero", "faq") without needing the full page envelope.
 *
 * Searches all polymorphic container slots (not just `section.components`)
 * via `ValidationRules.containerSlots` when available.
 *
 * @param pageSchema - The fully dereferenced page schema.
 * @param componentName - Name of the component (e.g. "hero").
 * @param options - Optional configuration including validationRules.
 * @returns A single-component schema envelope, or `null` if the component
 *   is not found.
 */
export function getComponentPresetSchema(
  pageSchema: Record<string, any>,
  componentName: string,
  options?: PrepareSchemaOptions
): OpenAiSchemaEnvelope | null {
  const { envelope } = prepareSchemaForOpenAi(pageSchema, {
    ...options,
    allowedComponents: [
      componentName,
      ...(options?.allowedComponents || ["section"]),
    ],
    sections: options?.sections || 1,
  });

  // Search all polymorphic slots for the target component
  const match = findComponentInSchema(envelope.schema, componentName);
  if (!match) return null;

  // Return a standalone schema for just that component
  return {
    name: `${componentName.replace(/-/g, "_")}_section`,
    strict: true,
    schema: match,
  };
}

/**
 * Return the list of component names available for AI generation.
 */
export function listAvailableComponents(): string[] {
  return [...SUPPORTED_COMPONENTS];
}

/**
 * Extract and prepare a single root-level field's sub-schema for OpenAI
 * structured output.
 *
 * This is used by `generate_root_field` and `generate_seo` to generate
 * content for individual root-level fields (e.g. `head`, `aside`, `cta`,
 * `seo`) without needing the full page schema.
 *
 * @param pageSchema - The fully dereferenced content type schema.
 * @param fieldName - Name of the root field to extract (e.g. `"head"`, `"seo"`).
 * @param contentType - Content type name for the envelope (e.g. `"blog-post"`).
 * @returns An OpenAI-compatible schema envelope, or `null` if the field
 *   doesn't exist in the schema.
 */
export function getRootFieldSchema(
  pageSchema: Record<string, any>,
  fieldName: string,
  contentType: string = "page"
): OpenAiSchemaEnvelope | null {
  const props = pageSchema.properties || {};
  const fieldSchema = props[fieldName];
  if (!fieldSchema) return null;

  // Clone so we don't mutate the caller's object
  const clonedFieldSchema = structuredClone(fieldSchema);

  // Run the same OpenAI-compatibility transforms on the sub-schema
  const cleanupPasses: TraverseCallback[] = [
    // Remove unsupported keywords
    (schema) => {
      for (const key of UNSUPPORTED_KEYWORDS) {
        if (Object.prototype.hasOwnProperty.call(schema, key)) {
          delete schema[key];
        }
      }
    },
    // Deny additional properties
    (schema) => {
      if (schema.type === "object") {
        schema.additionalProperties = false;
      }
    },
    // Make all properties required
    (schema) => {
      if (schema.type === "object" && schema.properties) {
        schema.required = Object.keys(schema.properties);
      }
    },
  ];

  for (const fn of cleanupPasses) {
    schemaTraverse(clonedFieldSchema, fn);
  }

  // Wrap the field schema in a top-level object envelope
  const envelopeName = `${contentType.replace(/-/g, "_")}_${fieldName.replace(
    /-/g,
    "_"
  )}`;

  return {
    name: envelopeName,
    strict: true,
    schema: clonedFieldSchema,
  };
}

// ─── Internal helpers ─────────────────────────────────────────────────

/**
 * Auto-detect root-level properties that should be excluded from AI
 * generation. Properties named `header`, `footer`, `token` are
 * typically layout / meta concerns that should not be generated.
 *
 * Note: `seo` is NOT excluded by default — it can be generated via the
 * dedicated `generate_seo` tool. Callers that want to exclude seo should
 * pass `rootPropertiesToExclude` explicitly or use the legacy behavior
 * by adding `"seo"` to the list.
 */
function detectDefaultExcludes(schema: Record<string, any>): string[] {
  const DEFAULT_EXCLUDE_NAMES = ["header", "footer", "token"];
  const props = schema.properties || {};
  return DEFAULT_EXCLUDE_NAMES.filter((name) => name in props);
}

/**
 * Find the first root-level array property in a schema.
 * Used as fallback when `rootArrayField` and `validationRules` aren't provided.
 */
function detectPrimaryRootArray(schema: Record<string, any>): string | null {
  const props = schema.properties || {};
  for (const [key, value] of Object.entries<any>(props)) {
    if (value && value.type === "array" && value.items) {
      return key;
    }
  }
  return null;
}

/**
 * Detect all root-level array field names from a schema.
 * Used as fallback when `validationRules.rootArrayFields` isn't provided.
 */
function detectRootArrayFields(schema: Record<string, any>): string[] {
  const fields: string[] = [];
  const props = schema.properties || {};
  for (const [key, value] of Object.entries<any>(props)) {
    if (
      value &&
      value.type === "array" &&
      value.items &&
      typeof value.items === "object"
    ) {
      fields.push(key);
    }
  }
  return fields;
}

/**
 * Recursively add `type` const properties to sub-component arrays
 * inside a container's items schema.
 *
 * This replaces the old hardcoded `section.items.properties.components.items`
 * path with a generic walk that finds all polymorphic `anyOf` slots.
 */
function addSubComponentTypeConsts(
  itemsSchema: Record<string, any>,
  subComponentMap: Record<string, string>
): void {
  if (!itemsSchema || typeof itemsSchema !== "object") return;

  const properties = itemsSchema.properties || {};

  for (const [_propKey, propValue] of Object.entries<any>(properties)) {
    if (!propValue || typeof propValue !== "object") continue;

    // Look for array properties with polymorphic items (anyOf)
    if (propValue.type === "array" && propValue.items?.anyOf) {
      for (const componentSchema of propValue.items.anyOf) {
        const componentName = componentSchema.$id
          ? getSchemaName(componentSchema.$id)
          : "";
        if (!componentName) continue;

        const arrayKey = subComponentMap[componentName];
        if (
          arrayKey &&
          componentSchema.properties?.[arrayKey]?.items?.properties
        ) {
          componentSchema.properties[arrayKey].items.properties.type = {
            const: arrayKey,
          };
        }
      }
    }
  }
}

/**
 * Search a prepared schema for a component by name in any polymorphic
 * `anyOf` slot. Returns the matching schema node or `null`.
 */
function findComponentInSchema(
  schema: Record<string, any>,
  componentName: string
): Record<string, any> | null {
  const props = schema.properties || {};

  for (const [_key, value] of Object.entries<any>(props)) {
    if (!value || typeof value !== "object") continue;

    // Check array items with anyOf
    if (value.type === "array" && value.items) {
      const items = value.items;

      // Direct anyOf on items
      if (items.anyOf) {
        const match = items.anyOf.find((s: any) => {
          const typeKey = Object.keys(s.properties || {}).find((k: string) =>
            k.startsWith("type__")
          );
          return typeKey === `type__${componentName}`;
        });
        if (match) return match;
      }

      // Nested: items.properties.*.items.anyOf (like section.components)
      if (items.properties) {
        for (const [_nestedKey, nestedValue] of Object.entries<any>(
          items.properties
        )) {
          if (nestedValue?.type === "array" && nestedValue?.items?.anyOf) {
            const match = nestedValue.items.anyOf.find((s: any) => {
              const typeKey = Object.keys(s.properties || {}).find(
                (k: string) => k.startsWith("type__")
              );
              return typeKey === `type__${componentName}`;
            });
            if (match) return match;
          }
        }
      }
    }
  }

  return null;
}
