/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {BlogTeaserProps} from "@kickstartds/design-system/blog-teaser";
import type {BusinessCardProps} from "@kickstartds/design-system/business-card";
import type {ContactProps} from "@kickstartds/design-system/contact";
import type {ContentNavProps} from "@kickstartds/design-system/content-nav";
import type {CtaProps} from "@kickstartds/design-system/cta";
import type {DividerProps} from "@kickstartds/design-system/divider";
import type {DownloadsProps} from "@kickstartds/design-system/downloads";
import type {EventLatestTeaserProps} from "@kickstartds/design-system/event-latest-teaser";
import type {EventListTeaserProps} from "@kickstartds/design-system/event-list-teaser";
import type {FaqProps} from "@kickstartds/design-system/faq";
import type {FeaturesProps} from "@kickstartds/design-system/features";
import type {GalleryProps} from "@kickstartds/design-system/gallery";
import type {HeroProps} from "@kickstartds/design-system/hero";
import type {HtmlProps} from "@kickstartds/design-system/html";
import type {ImageStoryProps} from "@kickstartds/design-system/image-story";
import type {ImageTextProps} from "@kickstartds/design-system/image-text";
import type {LogosProps} from "@kickstartds/design-system/logos";
import type {MosaicProps} from "@kickstartds/design-system/mosaic";
import type {SliderProps} from "@kickstartds/design-system/slider";
import type {SplitEvenProps} from "@kickstartds/design-system/split-even";
import type {SplitWeightedProps} from "@kickstartds/design-system/split-weighted";
import type {StatsProps} from "@kickstartds/design-system/stats";
import type {TeaserCardProps} from "@kickstartds/design-system/teaser-card";
import type {TestimonialsProps} from "@kickstartds/design-system/testimonials";
import type {TextProps} from "@kickstartds/design-system/text";
import type {VideoCurtainProps} from "@kickstartds/design-system/video-curtain";
import type {InfoTableProps} from "../info-table/InfoTableProps";
import type {PrompterProps} from "../prompter/PrompterProps";
import type {ButtonProps} from "@kickstartds/design-system/button";

/**
 * Width of section to use
 */
export type Width = "full" | "max" | "wide" | "default" | "narrow";
/**
 * Style of background
 */
export type Style = "default" | "framed" | "deko";
/**
 * Color of background
 */
export type Style1 = "default" | "accent" | "bold";
/**
 * Color of background
 */
export type Style2 = "none" | "to-default" | "to-accent" | "to-bold" | "to-inverted";
/**
 * Background image for the whole section
 */
export type BackgroundImage = string;
/**
 * Show spotlight behind cursor
 */
export type Spotlight = boolean;
/**
 * Amount of spacing before the section
 */
export type SpaceBefore = "default" | "small" | "none";
/**
 * Amount of spacing after the section
 */
export type SpaceAfter = "default" | "small" | "none";
/**
 * Whether to invert the section
 */
export type Inverted = boolean;
/**
 * Reserve additional spacing for a floating header
 */
export type HeaderSpacing = boolean;
/**
 * Headline Text for the section
 */
export type Headline = string;
/**
 * Make the headline larger
 */
export type LargeHeadline = boolean;
/**
 * Width of headline to use
 */
export type HeadlineWidth = "unset" | "narrow" | "default" | "wide";
/**
 * Choose the text alignment for the headline
 */
export type HeadlineTextAlignment = "left" | "center" | "right";
/**
 * Choose an alignment for positioning the headline
 */
export type HeadlineAlignment = "left" | "center" | "right";
/**
 * Subheadline for the section
 */
export type Subheadline = string;
/**
 * Switch the order of headline and subheadline
 */
export type SwitchHeadlineOrder = boolean;
/**
 * Width of content to use
 */
export type ContentWidth = "unset" | "narrow" | "default" | "wide";
/**
 * Choose an alignment for the content
 */
export type ContentAlignment = "left" | "center" | "right";
/**
 * Size of gutter to use
 */
export type Gutter = "large" | "default" | "small" | "none";
/**
 * Layout mode used for section contents
 */
export type Mode = "default" | "tile" | "list" | "slider";
/**
 * Set min-width for the tiles in the grid
 */
export type TileWidth = "smallest" | "default" | "medium" | "large" | "largest" | "full";
/**
 * Allowed components for content
 */
export type Content = (
  | BlogTeaserProps
  | BusinessCardProps
  | ContactProps
  | ContentNavProps
  | CtaProps
  | DividerProps
  | DownloadsProps
  | EventLatestTeaserProps
  | EventListTeaserProps
  | FaqProps
  | FeaturesProps
  | GalleryProps
  | HeroProps
  | HtmlProps
  | ImageStoryProps
  | ImageTextProps
  | LogosProps
  | MosaicProps
  | SliderProps
  | SplitEvenProps
  | SplitWeightedProps
  | StatsProps
  | TeaserCardProps
  | TestimonialsProps
  | TextProps
  | VideoCurtainProps
  | InfoTableProps
  | PrompterProps
)[];
/**
 * Buttons of the Button Group
 */
export type Buttons = ButtonProps[];
/**
 * If true, the section is marked as an AI-generated draft
 */
export type AIDraft = boolean;

/**
 * Component used to layout components into pages
 */
export interface SectionProps {
  width?: Width;
  style?: Style;
  backgroundColor?: Style1;
  transition?: Style2;
  backgroundImage?: BackgroundImage;
  spotlight?: Spotlight;
  spaceBefore?: SpaceBefore;
  spaceAfter?: SpaceAfter;
  inverted?: Inverted;
  headerSpacing?: HeaderSpacing;
  headline?: {
    text?: Headline;
    large?: LargeHeadline;
    width?: HeadlineWidth;
    textAlign?: HeadlineTextAlignment;
    align?: HeadlineAlignment;
    sub?: Subheadline;
    switchOrder?: SwitchHeadlineOrder;
  };
  content?: {
    width?: ContentWidth;
    align?: ContentAlignment;
    gutter?: Gutter;
    mode?: Mode;
    tileWidth?: TileWidth;
  };
  components?: Content;
  buttons?: Buttons;
  aiDraft?: AIDraft;
}
