/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Content navigation component for navigating related topics or sections within content.
 */
export interface ContentNavProps {
  image?: {
    /**
     * URL of the image to display in the content nav.
     */
    src: string;
    /**
     * Alternative text for the image.
     */
    alt?: string;
  };
  /**
   * The topic of the content being navigated.
   */
  topic?: string;
  links?: {
    /**
     * The text label for the link.
     */
    label: string;
    /**
     * The URL the link points to.
     */
    url: string;
  }[];
  /**
   * Determines how many links are initially shown in the content nav. If there are more links, a 'Show More' button will be displayed.
   */
  initiallyShown?: number;
}
