/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Title of the event
 */
export type Title = string;
/**
 * Label of the category
 */
export type Label = string;
/**
 * Categories associated with the event
 */
export type Categories = {
  label?: Label;
}[];
/**
 * Introductory text for the event
 */
export type Intro = string;

/**
 * Event header component for displaying event title, categories, and introductory text.
 */
export interface EventHeaderProps {
  title?: Title;
  categories?: Categories;
  intro?: Intro;
}
