/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pagination component for navigating through pages of content.
 */
export interface PaginationProps {
  truncate?: boolean;
  ariaLabels?: {
    /**
     * Aria label for the previous page link
     */
    previousPage?: string;
    /**
     * Aria label for the next page link
     */
    nextPage?: string;
    /**
     * Aria label for the link to skip to the first page
     */
    skipToFirstPage?: string;
    /**
     * Aria label for the link to skip to the last page
     */
    skipToLastPage?: string;
    /**
     * Aria label for the link to go to a specific page (will be placed before the page number)
     */
    goToPage?: string;
  };
  pages?: {
    /**
     * The URL to the page
     */
    url: string;
    /**
     * Indicates if the page is currently active
     */
    active?: boolean;
  }[];
}
