/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether to display the link to the search result.
 */
export type ShowLink = boolean;
/**
 * The reserved space of the image row.
 */
export type ImageRowSize = "none" | "small" | "large";

/**
 * Search form component for submitting search queries and displaying search results.
 */
export interface SearchFormProps {
  /**
   * ks-component attribute
   */
  component?: string;
  result?: {
    /**
     * Max number of subresults of a single search result
     */
    maxSubresults?: number;
    showLink?: ShowLink;
    imageColSize?: ImageRowSize;
  };
  resultPerPage?: number;
  moreButtonLabel?: string;
}
