/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of sections to generate
 */
export type SectionCount = number;
/**
 * Whether to include the current story as main context
 */
export type IncludeStory = boolean;
/**
 * Whether to use an idea as part of the context
 */
export type UseIdea = boolean;
/**
 * Additional related stories to include as context
 */
export type RelatedStories = string[];
/**
 * Custom prompt to guide content generation
 */
export type UserPrompt = string;
/**
 * System-level instructions for content generation
 */
export type SystemPrompt = string;

/**
 * Component used to create new website content using Prompter prompts
 */
export interface PrompterProps {
  sections?: SectionCount;
  includeStory?: IncludeStory;
  useIdea?: UseIdea;
  relatedStories?: RelatedStories;
  userPrompt?: UserPrompt;
  systemPrompt?: SystemPrompt;
}
