/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the visual
 */
export type Headline = string;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Visually highlight the text
 */
export type HighlightText = boolean;
/**
 * Make the text and buttons color neutral
 */
export type ColorNeutral = boolean;
export type Height = "small" | "default" | "fullImage" | "fullScreen";
/**
 * Toggle wether you want your text to be displayed within in box
 */
export type Textbox = boolean;
/**
 * On mobile devices, display the text below the image
 */
export type MobileTextBelow = boolean;
/**
 * Invert the text color for better contrast against the background
 */
export type InvertText = boolean;
/**
 * Text content to display inside the button
 */
export type Label = string;
/**
 * Choose an icon
 */
export type Icon = string;
/**
 * The URL to link to when the button is clicked
 */
export type URL = string;
/**
 * Add a skip button to the hero module
 */
export type SkipButton = boolean;
/**
 * Enable grid layer
 */
export type GridLayer = boolean;
/**
 * Background image source for small screens
 */
export type MobileImageSource = string;
/**
 * Background image source for medium screens
 */
export type TabletImageSource = string;
/**
 * Background image source for large screens
 */
export type DesktopImageSource = string;
/**
 * Override for img tag of picture element, if needed
 */
export type OptionalSource = string;
/**
 * Choose to indent the image horizontally on small screens
 */
export type ImageIndent = "none" | "left" | "right";
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Choose the alginment of the module content
 */
export type ModuleAligment = "center" | "below" | "offset" | "left" | "right" | "corner" | "bottom";

/**
 * Hero component for displaying a prominent visual section with headline, subheadline, text, and call-to-action buttons.
 */
export interface HeroProps {
  headline?: Headline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  highlightText?: HighlightText;
  colorNeutral?: ColorNeutral;
  height?: Height;
  textbox?: Textbox;
  mobileTextBelow?: MobileTextBelow;
  invertText?: InvertText;
  buttons?: Button[];
  skipButton?: SkipButton;
  overlay?: GridLayer;
  image?: BackgroundImage;
  textPosition?: ModuleAligment;
}
export interface Button {
  label?: Label;
  icon?: Icon;
  url?: URL;
}
/**
 * Sources of background images for different screen sizes
 */
export interface BackgroundImage {
  srcMobile: MobileImageSource;
  srcTablet?: TabletImageSource;
  srcDesktop?: DesktopImageSource;
  src?: OptionalSource;
  indent?: ImageIndent;
  alt?: AltText;
}
