/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Headline for the event login
 */
export type Headline = string;
/**
 * Text for the event login
 */
export type Text = string;
/**
 * Label for the password input
 */
export type Label = string;
/**
 * Placeholder text for the email input
 */
export type Placeholder = string;
/**
 * Label for the call to action button
 */
export type ButtonLabel = string;
/**
 * Aria label for the cta button
 */
export type AriaLabel = string;
/**
 * Text for the reset password link
 */
export type Label1 = string;
/**
 * URL for the reset password link
 */
export type URL = string;

/**
 * Event login component for user authentication to access event-related content.
 */
export interface EventLoginProps {
  headline?: Headline;
  text?: Text;
  usernameInput?: UsernameInput;
  passwordInput?: PasswordInput;
  cta?: CallToAction;
  resetPassword?: ResetPassword;
}
/**
 * Input field for the username
 */
export interface UsernameInput {
  label?: string;
  placeholder?: string;
}
/**
 * Input field for the password
 */
export interface PasswordInput {
  label?: Label;
  placeholder?: Placeholder;
}
export interface CallToAction {
  label?: ButtonLabel;
  url?: string;
  ariaLabel?: AriaLabel;
}
/**
 * Link to reset password
 */
export interface ResetPassword {
  label?: Label1;
  url?: URL;
}
