/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Downloads component for providing users with downloadable files and resources.
 */
export interface DownloadsProps {
  download?: {
    /**
     * The name of the file
     */
    name: string;
    /**
     * A brief description of the file
     */
    description?: string;
    /**
     * A URL to an image that previews the file.
     */
    previewImage?: string;
    /**
     * The URL to download the file from.
     */
    url: string;
    /**
     * The size of the download file
     */
    size?: string;
    /**
     * The format of the download file
     */
    format?: string;
  }[];
}
