/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventFilterProps} from "../event-filter/EventFilterProps";
import type {EventListTeaserProps} from "../event-list-teaser/EventListTeaserProps";

/**
 * Event list component for displaying a list of events with filtering options.
 */
export interface EventListProps {
  /**
   * Referenced component EventFilterProps
   */
  filter?: EventFilterProps;
  events?: EventListTeaserProps[];
}
