/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {HeaderProps} from "../header/HeaderProps";
import type {FooterProps} from "../footer/FooterProps";
import type {SeoProps} from "../seo/SeoProps";

/**
 * Content of the icon sprite for this project
 */
export type IconSprite = string;
/**
 * CSS custom property overrides to be included in the global styles — layers on top of the selected theme
 */
export type CSSCustomPropertyOverrides = string;
/**
 * Whether to hide breadcrumbs across the site
 */
export type HideBreadcrumbs = boolean;

/**
 * Abstracts global settings made for a website into JSON Schema
 */
export interface SettingsProps {
  /**
   * Referenced component HeaderProps
   */
  header: HeaderProps;
  /**
   * Referenced component FooterProps
   */
  footer: FooterProps;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
  iconSprite?: IconSprite;
  token?: CSSCustomPropertyOverrides;
  hideBreadcrumbs?: HideBreadcrumbs;
}
