/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {EventLatestTeaserProps} from "../event-latest-teaser/EventLatestTeaserProps";

/**
 * List of events to display
 *
 * @minItems 1
 */
export type Events = [EventLatestTeaserProps, ...EventLatestTeaserProps[]];

/**
 * Display a list of latest events, ordered chronologically
 */
export interface EventLatestProps {
  events?: Events;
  className?: string;
}
