declare module "@kickstartds/form/lib/radio-group/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The label for the element
 */
export type Label = string;
/**
 * The name of the input element, used when submitting an HTML form
 */
export type Name = string;
/**
 * Wheter the input is invalid
 */
export type Invalid = boolean;
/**
 * Message to show if the input is invalid
 */
export type InvalidMessage = string;
/**
 * Whether the input is disabled
 */
export type Disabled = boolean;
/**
 * Help text that gives more context about what a user needs to input
 */
export type HintMessage = string;
export type Options = RadioButton[];
/**
 * Additional css classes attached to the input element
 */
export type Class = string;

/**
 * Radioes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.
 */
export interface RadioGroupProps {
  label: Label;
  name?: Name;
  invalid?: Invalid;
  invalidMessage?: InvalidMessage;
  options?: Options;
  className?: Class;
}
/**
 * Radio buttons allow users to select a single option from a list of mutually exclusive options.
 */
export interface RadioButton {
  label: Label;
  disabled?: Disabled;
  hint?: HintMessage;
}

}
      